export const MAX_METADATA_LENGTH = 500;
export const MAX_TELEMETRY_LOG_SIZE = 30;
export const MAX_TELEMETRY_MESSAGE_LENGTH = 10_000;
export const MAX_TELEMETRY_URI_LENGTH = 1_000;
export const MAX_TELEMETRY_ATTRIBUTES = 20;
export const MAX_TELEMETRY_ATTRIBUTE_VALUE = 500;